# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |v|
  v.customize ["modifyvm", :id, "--memory", 1024]
  end

  config.vm.define "asterisk_pbx" do |asterisk_pbx|
    asterisk_pbx.vm.hostname = 'asterisk-pbx'  
    asterisk_pbx.vm.network :private_network, ip: "10.0.123.2"
  end
end
